name: Log Issue Manager
env:
  TODAY: ''
  YM: ''
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'
jobs:
  manage-issue:
    name: Manage Log Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make the Script file executable
        run: chmod +x .github/scripts/generate-github-token.sh
      - name: Generate GitHub Apps token
        id: generate
        run: |
          .github/scripts/generate-github-token.sh
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: Set Today's date
        run: echo "TODAY=$(date -d tomorrow '+%Y/%m/%d')" >> $GITHUB_ENV
      - name: Set current year and month
        id: date
        run: echo "YM=$(date '+%Y-%m')" >> $GITHUB_ENV
      - name: Manage Issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_numbers=$(gh issue list \
              --label "log" \
              --json number \
              --search "created:>=$(date -d yesterday '+%Y-%m-%d')" \
              --jq '.[].number')
            echo "Previous issue numbers: $previous_issue_numbers"
            for previous_issue_number in $previous_issue_numbers; do
              if [[ -n $previous_issue_number ]]; then
                comment_count=$(gh issue view "$previous_issue_number" --json comments --jq '.comments | length')
                if [[ $comment_count -eq 0 ]]; then
                  gh issue delete "$previous_issue_number" \
                    --yes
                else
                  gh issue close "$previous_issue_number"
                  gh issue unpin "$previous_issue_number"
                fi
              fi
            done
          fi
          if ! gh label list --json name | jq -r '.[].name' | grep -q "log"; then
            gh label create log
          fi
          if ! gh label list --json name | jq -r '.[].name' | grep -q $YM; then
            gh label create $YM
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TITLE: "[log]${{ env.TODAY }}"
          ASSIGNEES: ${{ github.repository_owner }}
          LABELS: "log,${{ env.YM }}"
          BODY: |
            _Not everything can be written freely._
            [Issues](https://github.com/borntoolate/tasukete/issues)
          PINNED: false
          CLOSE_PREVIOUS: true
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"